image: cypress/base:12.14.0

pipelines:
  branches:
    latte-reference:
      - step:
          name: Checkout code
          caches:
            - node
          script:
            - npm install --legacy-peer-deps

      - step:
          name: Run Cypress tests
          services:
            - docker
          caches:
            - node
          script:
            - npm Cypress run

    master:
      - step:
          name: Checkout code
          caches:
            - node
          script:
            - npm install --legacy-peer-deps

      - step:
          name: Run Cypress tests
          services:
            - docker
          caches:
            - node
          script:
            - npm Cypress run

definitions:
  caches:
    node: ~/.npm
  services:
    docker:
      memory: 1024
