image: cypress/included:13.8.1

pipelines:
  branches:
    latte-reference:
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install --legacy-peer-deps
            - npm install start-server-and-test --save-dev

      - step:
          name: Start server and run Cypress tests
          services:
            - docker
          caches:
            - node
          script:
            - npx start-server-and-test start-18 http://127.0.0.1:3000 cypress:run

    master:
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install --legacy-peer-deps
            - npm install start-server-and-test --save-dev

      - step:
          name: Start server and run Cypress tests
          services:
            - docker
          caches:
            - node
          script:
            - npx start-server-and-test start-18 http://127.0.0.1:3000 cypress:run

definitions:
  caches:
    node: ~/.npm
  services:
    docker:
      memory: 1024
