image: cypress/included:13.8.1

pipelines:
  branches:
    latte-reference:
      - step:
          name: Checkout code
          caches:
            - node
          script:
            - npm install --legacy-peer-deps

      - step:
          name: Run Cypress tests
          services:
            - docker
          caches:
            - node
          script:
            - npm run dev

    master:
      - step:
          name: Checkout code
          caches:
            - node
          script:
            - npm install --legacy-peer-deps

      - step:
          name: Run Cypress tests
          services:
            - docker
          caches:
            - node
          script:
            - npm run dev
definitions:
  caches:
    node: ~/.npm
  services:
    docker:
      memory: 1024
