image: cypress/base:10

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - node
        script:
          - npm install --legacy-peer-deps

    - step:
        name: Run Cypress tests
        services:
          - docker
        caches:
          - node
        script:
          - npx cypress run

definitions:
  caches:
    node: ~/.npm
  services:
    docker:
      memory: 1024
