image: cypress/included:13.8.1

pipelines:
  branches:
    latte-reference:
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install --legacy-peer-deps

      - step:
          name: Start server and run Cypress tests
          services:
            - docker
          caches:
            - node
          script:
            - npm run start-18 & # Start the server in the background
            - npx wait-on http://127.0.0.1:3000 # Wait for the server to be ready
            - npx cypress run # Run Cypress tests

    master:
      - step:
          name: Install dependencies
          caches:
            - node
          script:
            - npm install --legacy-peer-deps

      - step:
          name: Start server and run Cypress tests
          services:
            - docker
          caches:
            - node
          script:
            - npm run start-18 & # Start the server in the background
            - npx wait-on http://127.0.0.1:3000 # Wait for the server to be ready
            - npx cypress run # Run Cypress tests

definitions:
  caches:
    node: ~/.npm
  services:
    docker:
      memory: 1024
