image: cypress/base:10

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - node
        script:
          - npm install --legacy-peer-deps
          - npm ci
          # start the server in the background
          - npm run start &
          # run Cypress tests
          - npm run e2e
definitions:
  caches:
    node: ~/.npm
  services:
    docker:
      memory: 1024

