name: ci
on: [push]
jobs:
  # run end-to-end tests using the standard workflow
  # https://github.com/bahmutov/cypress-workflows
  e2e:
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
    with:
      # check the spec types in the "build" step
      # since we don't have any specific build for our app
      # don't forget to start the application
      # and wait for the "http://127.0.0.1:3000" to respond
      # Note: GitHub Actions have Node v18 installed
      build: npm run lint
      start: npm run start-18
      wait-on: 'http://127.0.0.1:3000'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run lint
        run: npm run lint

      - name: Start application
        run: npm run start-18 &

      - name: Wait for application
        uses: jakejarvis/wait-action@v1
        with:
          url: 'http://127.0.0.1:3000'

      - name: Run Cypress tests
        run: npm run cypress:run

  # in a separate job, run component tests
  # using the standard workflow
  # https://github.com/bahmutov/cypress-workflows
  components:
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
    with:
      component: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run component tests
        run: npm run cypress:run --component
